#!/usr/bin/expect -f
set password "123"
set host "192.168.64.4"
set user "jetauto"
set timeout 600

set cmd {
sudo apt update && \
sudo apt install -y ros-melodic-navigation ros-melodic-explore-lite ros-melodic-magic-enum-dev
}

spawn ssh -t -o StrictHostKeyChecking=no $user@$host $cmd
expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    "password for jetauto:" {
        send "$password\r"
        exp_continue
    }
    eof
}
