#!/usr/bin/expect -f
set password "123"
set host "192.168.64.4"
set user "jetauto"
set key_path "/Users/kevinwang/.ssh/id_rsa_jetauto"
set timeout 30

set cmd {
sudo sed -i 's/HOST="/HOST="192.168.64.4/' /etc/environment && \
sudo sed -i 's/MASTER="/MASTER="192.168.64.4/' /etc/environment && \
cat /etc/environment
}

spawn ssh -t -i $key_path -o StrictHostKeyChecking=no $user@$host $cmd
expect {
    "password for jetauto:" {
        send "$password\r"
        exp_continue
    }
    eof
}
